all:
  hosts:
    node1:
      ansible_host: 188.166.70.44
      ip: 188.166.70.44
      access_ip: 188.166.70.44
    node2:
      ansible_host: 167.99.33.100
      ip: 167.99.33.100
      access_ip: 167.99.33.100
    node3:
      ansible_host: 188.166.72.200
      ip: 188.166.72.200
      access_ip: 188.166.72.200
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
